[build]
  publish = "."
  command = "echo 'Static site ready'"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"]}

# Handle SPA routing
[[redirects]]
  from = "/recipe"
  to = "/recipe.html"
  status = 200

[[redirects]]
  from = "/favorites"
  to = "/favorites.html"
  status = 200

[[redirects]]
  from = "/planner"
  to = "/planner.html"
  status = 200

[[redirects]]
  from = "/nutrition"
  to = "/nutrition.html"
  status = 200

[[redirects]]
  from = "/surprise"
  to = "/surprise.html"
  status = 200
